### ISSUE TITLE
Tìm hiểu Github Action tự động CI/CD

### ISSUE THREAD

**Issue by Hunter1202** [Hunter1202/se2022-15.2#11]

**Comment by BToopS2** [comment]
CI/CD là gì ? 
Theo định nghĩa đúng của nó là CI là Continuous Integration (tích hợp liên tục) và CD là Continuous Delivery (phân phối liên tục). Ây dà, sao nghe có vẻ hàn lâm quá vậy nè. Từ từ mình giải thích từng cái một nha.

Ví dụ team bạn có nhiều người, mỗi người code một chức năng ở mỗi branch khác nhau. Khi một người code xong commit lên git, bạn phải review code, rồi test chức năng vừa mới bổ sung và những chức năng cũ, cuối cùng là tạo pull request. Giả sử team bạn nhiều người thì sao nhở, bạn phải làm toàn bộ những công việc trên bằng tay à, à đúng rồi đấy. Vậy là người ta đưa ra khái niệm CI là tích hợp liên tục, bao gồm cả build, test, có thể là unit test hoặc integration test, sau khi build và test xong thì nó sẽ gửi thông báo hay gì đó tuỳ cấu hình, sau đó nó sẽ chuyển sang đoạn tiếp theo là CD.

Phân phối liên tục được hiểu theo một cách đơn giản nhất là tự động deloy ứng dụng của bạn lên server, CD có thể nằm riêng, hoàn toàn không phụ thuộc vào CI, nhưng mà trên thực tế thì CI/CD là một quy trình làm việc, code của bạn sẽ được build test và sau đó deloy trên server hoặc cloud một cách tự động luôn.

Có một ví trí cho công việc này trong dự án gọi là DevOps là người sẽ phụ trách phần này, kết nối giữa việc Develop (phát triển) và Operation (vận hành). Hiểu nôm na là người sẽ phụ trách CI/CD này luôn.

Việc ứng dụng CI/CD sẽ giúp chúng ta gia tăng năng xuất và chất lượng cho sản phẩm phần mềm bằng việc phát hiện và cảnh báo sớm những rủi ro, đưa ứng dụng deloy một cách nhanh chóng và tiết kiệm thời gian nhất có thể. Nghe đến đây chắc bạn cũng có đủ hứng thú để bắt tay vào thực hiện rồi đúng không, mình sẽ demo thử CI với GitHub Action nha.

CI với GitHubAction

**Comment by BToopS2** [comment]
**CI với GitHubAction**
https://codelearn.io/sharing/cicd-voi-github-action-phan-1

**Comment by Thefuckingdead** [comment]
# Mục Lục
**1.** CI/CD là gì ? 
**2.** CI 

## 1.CI/CD là gì ?

**1.1.** CI ?
&nbsp;&nbsp;&nbsp;&nbsp; Về cơ bản CI là viết tắt của từ Continuous Integration (Tích hợp liên tục).  Nó là phương pháp phát triển phần mềm yêu cầu các thành viên của team tích hợp công việc của họ thường xuyên, mỗi ngày ít nhất một lần. Mỗi tích hợp được "build" tự động (bao gồm cả test) nhằm phát hiện lỗi nhanh nhất có thể. Cả team nhận thấy rằng cách tiếp cận này giảm thiểu vấn đề tích hợp và cho phép phát triển phần mềm nhanh hơn.
&nbsp;&nbsp;&nbsp;&nbsp; Quy trình CI hoạt động được thực hiện thông qua các bước sau:

1. Đầu tiên, developer commit code lên repo.
2. CI server giám sát repo và kiểm tra xem liệu có thay đổi nào trên repo hay không (liên tục, chẳng hạn mỗi phút 1 lần)
3. Ngay khi commit xảy ra, CI server phát hiện repo có thay đổi, nên nó nhận code mới nhất từ repo và sau đó build, chạy unit và integration test
4. CI server sẽ sinh ra các feedback và gửi đến các member của project
5. CI server tiếp tục chờ thay đổi ở repo

&nbsp;&nbsp;&nbsp;&nbsp; Dưới đây là 1 hình minh hoạ cho quy trình CI:

![CI life cycle](https://www.techuz.com/blog/wp-content/uploads/2019/06/CI-CD_Continuous-Integration.jpg)

**1.2.** CD ?
&nbsp;&nbsp;&nbsp;&nbsp; CD là viết tắt của từ Continuous Delivery (phân phối liên tục). bằng cách triển khai tất cả thay đổi về code (đã được build và test) đến môi trường testing hoặc staging. Continuous Delivery cho phép developer tự động hóa phần testing bên cạnh việc sử dụng unit test, kiểm tra phần mềm qua nhiều thước đo trước khi triển khai cho khách hàng (production). Những bài test này bao gồm UI testing, load testing, integration testing, API testing... Nó tự động hoàn toàn quy trình release phần mềm.
&nbsp;&nbsp;&nbsp;&nbsp; Ngoài ra CD Cũng dùng để viết tắt cho Continuous Deployment (Triển khai liên tục). Cũng tương tự như Continuous Delivery về các vấn đề khác ngoại trừ việc Continuous Delivery phải thủ công triển khai code lên môi trường production thì Continuous Deployment sẽ tự động triển khai code lên môi trường production.
![ci cd asset updates  007](https://user-images.githubusercontent.com/95278548/211038894-b3eaa00c-1cb4-42eb-b5cd-c00536e72b03.png)

## 2. Github Action cho CI/CD
&nbsp;&nbsp;&nbsp;&nbsp; **Tài liệu nghiên cứu** : [github action](https://docs.github.com/en/actions)
&nbsp;&nbsp;&nbsp;&nbsp; **File demo helloworld.yaml**:
```name: hello wolrd
on:
  push: 
    branches: [main]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World
 ```
&nbsp;&nbsp;&nbsp;&nbsp;**Video test**:

https://user-images.githubusercontent.com/95278548/211045137-243520db-5ace-4348-9b51-fafdef1d2b23.mp4

**Comment by TeamTCV1** [comment]
1. CI (Continuous integration)

- Continuous integration đưa ra một quy trình cho các thành viên trong nhóm triển khai cập nhật cho một sản phẩm phần mềm. Ban đầu, tất cả mã do các thành viên riêng lẻ viết được kết hợp với nhau. Quy trình CI đảm bảo rằng mã tích hợp này đã vượt qua tất cả các danh sách kiểm tra cần thiết cho business logic, coding và testing, đồng thời được hợp nhất trong một nhánh kho lưu trữ chung.
- Với mô hình phát triển phần mềm linh hoạt, CI cho phép một quy trình liền mạch. Nó đảm bảo rằng các thành viên làm việc cùng nhau để tạo ra những cải tiến nhỏ cho sản phẩm thông qua các bản cập nhật liên tục. Do đó, từ “Continuous” có liên quan trong quy trình CI. 
- Khi được thực hiện đúng, CI giống như một đường dẫn quy trình trong đó mã nguồn đại diện cho đóng góp của từng nhà phát triển được cung cấp từ một đầu. Một mã sản phẩm phần mềm tích hợp xuất hiện ở đầu bên kia. Một số nhiệm vụ tiêu chuẩn của quy trình CI bao gồm kiểm tra chất lượng mã, đánh giá mã, unit testing và hợp nhất.

![Image](https://user-images.githubusercontent.com/95847728/217475217-65bc41f2-45dd-45d0-a110-2353e6c9fb8e.png)

- Ở hình minh họa trên ột số bước CI giống như các đường dẫn song song giống như các hoạt động được thực hiện bởi mỗi thành viên. Sau khi tất cả mã được hợp nhất, quy trình sẽ trở thành một luồng duy nhất ở cuối CI.
- Mục tiêu chính của quy trình CI là tăng cường sự hợp tác giữa tất cả các thành viên trong nhóm để đảm bảo tuân thủ các quy trình phát triển phần mềm, kiểm soát chất lượng và xác thực tất cả các tính năng cũng như bản sửa lỗi đang được triển khai. Kết quả cuối cùng là một gói xây dựng phần mềm đã sẵn sàng để trải qua các quy trình tiếp theo như một phần của đĩa CD. 

2.CD (Continuous Delivery hay Continuous Deployment)

- CD là quá trình tiếp theo ngay sau CI, nó thực hiện các hoạt động bổ sung cho đến khi chuyển giao sản phẩm phần mềm cuối cùng
- Hai nhiệm vụ chính của CD:
  + Automation Testing: Mặc dù quy trình CI đảm bảo rằng các mô-đun riêng lẻ được kiểm tra đơn vị để xác thực các yêu cầu về tính năng, nhưng quy trình này có thể không giải quyết hoàn toàn sự tích hợp tổng thể của tất cả các mô-đun trong sản phẩm phần mềm. Do đó, đường dẫn CD thực hiện thử nghiệm tích hợp trên gói bản dựng do CI tạo. Nó đảm bảo tuân thủ tất cả các yêu cầu đối với việc xây dựng sản phẩm tích hợp. Ngoài ra, CD cũng duy trì cảnh giác để đảm bảo rằng các tính năng sản phẩm hiện có không bị ảnh hưởng do những thay đổi mới.
  + Management of Hosting Environments: Là điều kiện tiên quyết để lưu trữ phần mềm, CD cũng phải thiết lập và duy trì các môi trường lưu trữ khác nhau giống như cấu hình thực của sản phẩm phần mềm. Các môi trường này được sinh ra với các cài đặt khác nhau để hỗ trợ kiểm tra các yêu cầu chức năng và phi chức năng.
- Do các yêu cầu nghiêm ngặt về hiệu suất và khả năng mở rộng để lưu trữ một sản phẩm phần mềm dựa trên SaaS, CD thường được chia thành nhiều các giai đoạn thử nghiệm để kiểm tra các yêu cầu này. Mỗi giai đoạn được liên kết với một môi trường lưu trữ và CD được định cấu hình để di chuyển gói xây dựng phần mềm từ giai đoạn này sang giai đoạn tiếp theo.


![Image](https://user-images.githubusercontent.com/95847728/217479853-9cfb1564-af8e-454a-899b-300be7a310f8.png)

- Bước cuối cùng trong quy trình CD là cung cấp bản phát hành phần mềm chính thức. Tại thời điểm này, gói xây dựng phần mềm mới tạo được triển khai trên môi trường lưu trữ.
