### ISSUE TITLE
Trang trí  README.MD

### ISSUE THREAD

**Issue by Hunter1202** [Hunter1202/se2022-15.2#12]

**Comment by BToopS2** [comment]
Statting........

**Comment by BToopS2** [comment]
Logo is completing.....

**Comment by BToopS2** [comment]
Logo is completed

**Comment by BToopS2** [comment]
Visual effects is comming...

**Comment by BToopS2** [comment]
added visual effects

**Comment by BToopS2** [comment]
link : https://thuthuatphanmem.vn/50-anh-gif-cuc-dep/

youtube, google, ...etc..

**Comment by BToopS2** [comment]
added soure code Dockerfile in README file
