### ISSUE TITLE
Tìm hiểu Docker, Docker Compose

### ISSUE THREAD

**Issue by Hunter1202** [Hunter1202/se2022-15.2#2]
📑 Tài liệu :
- ae học Docker qua video này nhé: https://www.youtube.com/watch?v=3c-iBn73dDE
- Đăng ký tài khoản AWS: https://aws.amazon.com/

**Comment by Hunter1202** [comment]
- ae học Docker qua video này nhé: https://www.youtube.com/watch?v=3c-iBn73dDE
- Đăng ký tài khoản AWS: https://aws.amazon.com/

**Comment by BToopS2** [comment]
oke nhe

**Comment by Hunter1202** [comment]
thoát ra, rồi đăng nhập lại là được nhé, tôi thử r

**Comment by Thefuckingdead** [comment]
[https://www.youtube.com/watch?v=FzwIs2jMESM](url)
A e học docker bằng đường link này đi dễ hiểu phết

**Comment by Hunter1202** [comment]
Ae tóm tắt ngắn gọn về các khái niệm của Docker vào đây nhé

**Comment by BToopS2** [comment]
Container là gì?
         Container là đơn vị phần mềm cung cấp cơ chế đóng gói ứng dụng, mã nguồn, thiết lập, thư viện… vào một đối tượng duy nhất. Ứng dụng sau khi được đóng gói có thể hoạt động một cách nhanh chóng và hiệu quả trên các môi trường điện toán khác nhau. Từ đó nó có thể tạo ra một môi trường hoàn hảo nơi mà có mọi thứ để chương trình có thể hoạt động được, không chịu sự tác động từ môi trường của hệ thống cũng như không làm ảnh hưởng ngược lại về phía hệ thống chứa nó.
          
Để tạo ra container phải kể đến 2 tính năng có trong nhân Linux đó là:

Namespace: có nhiệm vụ cô lập các tài nguyên của hệ thống, khiến các tiến trình "nhìn thấy" tập tài nguyên khác nhau.
Control groups (cgroups): giới hạn tài nguyên của mỗi ứng dụng, cho phép Docker Engine điều phối lượng tài nguyên phần cứng của mỗi ứng dụng, thiết lập các ràng buộc.
Các tiến trình (process) trong một container sẽ cô lập với tiến trình của các container khác trong cùng một hệ thống. Tuy nhiên, tất cả các container này đều chia sẻ kernel của host OS.

**Comment by BToopS2** [comment]
Các thuật ngữ thường gặp trong Docker:
#Docker Image: 
     Một Docker Image là một read-only template dùng để tạo ra các containers. Image được cấu tạo theo dạng layer và tất cả các layer đều là read-only. Một image có thể được tạo ra dựa trên một image khác với một số tùy chỉnh bổ sung. Nói ngắn gọn, Docker Image là nơi lưu trữ các cài đặt môi trường như OS, package, phần mềm cần chạy, …
Nếu nhìn nhận theo lập trình hướng đối tượng thì Docker Image giống như một class chứa các phương thức và thuộc tính, còn các containers là các thực thể (instance/object) của các class đó. Vì vậy từ 1 image chúng ta có thể tạo ra nhiều containers với môi trường bên trong giống hệt nhau.

#Dockerfile: 
    Dockerfile là một file dạng text không có phần đuôi mở rộng, chứa các đặc tả về một trường thực thi phần mềm, cấu trúc cho Docker image. Từ những câu lệnh đó, Docker sẽ build ra Docker image (thường có dung lượng nhỏ từ vài MB đến lớn vài GB).
#Docker Container:
       Docker Container được tạo ra từ Docker Image, là nơi chứa mọi thứ cần thiết để có thể chạy ứng dụng. Là ảo hóa nhưng Container lại rất nhẹ, có thể coi như là một process của hệ thống. Chỉ mất vài giây để start, stop hoặc restart một Container. Với một máy chủ vật lý, thay vì chạy được vài cái máy ảo truyền thống thì ta có thể chạy vài chục, thậm chí vài trăm cái Docker Container.

Các trạng thái có thể có: run, started, stopped, moved và deleted.

Ví dụ, container có thể chứa môi trường:
OS: Ubuntu 18.04
Package: cài sẵn git, curl, vim, nano, …
Cài ứng dụng cần thực thi


#Docker Network
        Docker network có nhiệm vụ cung cấp private network (VLAN) để các container trên một host có thể liên lạc được với nhau, hoặc các container trên nhiều hosts có thể liên lạc được với nhau (multi-host networking).

#Docker Volume:
       Docker volume là cơ chế tạo và sử dụng dữ liệu của docker, có nhiệm vụ lưu trữ dữ liệu độc lập với vòng đời của container.

Có 3 trường hợp sử dụng Docker Volume:

Giữ lại dữ liệu khi một Container bị xóa.
Để chia sẻ dữ liệu giữa máy chủ vật lý và Docker Container.
Chia sẻ dữ liệu giữa các Docker Container.

#Docker Compose:
                Docker compose là công cụ dùng để định nghĩa và run multi-container cho Docker application. Với compose bạn sử dụng file YAML để config các services cho application của bạn. Sau đó dùng command để create và run từ những config đó.

Sử dụng cũng khá đơn giản chỉ với ba bước:

Khai báo app’s environment trong Dockerfile.
Khai báo các services cần thiết để chạy application trong file docker-compose.yml.
Run docker-compose up để start và run app.



#Docker Hub
Nếu bạn là developer thì chắc hẳn bạn đã quen với công cụ github dùng để upload code của mình lên đó, hiểu đơn giản thì Docker hub cũng tương tự như github nhưng dành cho DockerFile, Docker Images. Ở đây có những DockerFile, Images của người dùng cũng như những bản chính thức từ các nhà phát triển lớn như Google, Oracle, Microsoft, … Ngoài ra còn có Docker Hub cho phép quản lý các image với những câu lệnh giống như Github như push, pull... để bạn có thể quản lý dễ dàng image của mình.

**Comment by BToopS2** [comment]
Các thành phần của Docker Engine gồm có:

Docker Deamon: chạy trên host, đóng vai trò là server, nhận các RESTful request từ Docker Client và thực thi nó. Là một lightweight runtime giúp build, run và quản lý các containers và các thành phần liên quan khác.
Docker Deamon quản lý 4 đối tượng chính: image, container, network, volume.

Docker Client (CLI): cung cấp giao diện dòng lệnh (command line) cho người sử dụng, đồng thời cũng gửi request đến Docker deamon.



Docker Registry: nơi lưu trữ Docker image. Docker Hub là một registry công khai mà bất cứ ai cũng có thể sử dụng và Docker được cấu hình để tìm kiếm image trên Docker Hub theo mặc định. Bạn thậm chí có thể chạy registry riêng của mình. Có hai loại registry là public hoặc private registry.

**Comment by BToopS2** [comment]
![img](https://images.viblo.asia/666442ed-c0e5-46f8-83c4-a337038c92c5.png)


---------------------
##Kiến trúc của Docker

![image](https://user-images.githubusercontent.com/95840866/209775716-98d2ea33-9042-457e-8fc5-e645aa4ec5ea.png)
--------------
Sơ đồ minh họa các lệnh phổ biến của Docker client và mối quan hệ của Image, Container, Network, Volume.
![img](https://images.viblo.asia/bd07ffdc-0c4b-4e0f-af1b-6c7f68a18490.png)

**Comment by Thefuckingdead** [comment]
# Các thuật ngữ cơ bản trong Docker cần biết
1. Docker Image
2. Docker Container
3. Dockerfile
4. Docker Volume
5. Docker Compose
## 1. Docker Image 
 ``` Về cơ bản Docker Image là một khuôn mẫu (nguyên mẫu) chỉ có thể xem không chạy được.```

 &nbsp;&nbsp;&nbsp;&nbsp;Nó giống như kiểu chỉ là một cái xác, 1 cái vỏ bọc bên ngoài vậy. Image được cấu tạo theo dạng các lớp được xếp chồng lên nhau và tất nhiên tất cả các lớp như vậy chỉ đọc được. Từ một image chúng ta có thể tạo ra được nhiều container khác nhau bằng cách thực thi các câu lệnh giống như là bỏ hồn vào trong cái xác vậy. 
## 2. Docker Container
```Docker Container là các tiến trình được đóng hộp chạy 1 cách riêng biệt trên máy tính.```

&nbsp;&nbsp;&nbsp;&nbsp;Dù có những tính năng tương tự như ảo hoá nhưng một điều rất hay của việc sử dụng các docker container là chúng rất nhẹ khi so sánh với ảo hoá. Do đó các bước khởi động, tắt, ngắt được thực hiện một cách rất nhanh chóng. Giúp tiết kiệm được thời gian và tài nguyên.
## 3. Dockerfile
``` Dockerfile là một dạng file dùng để chứa các mô tả về việc thực thi phần mềm để tạo ra các image ```

&nbsp;&nbsp;&nbsp;&nbsp;Nói một cách khái quát thì chúng ta có thể sử dụng các lệnh riêng lẻ để tạo ra được Docker Image . Tuy nhiên cách này khá tốn thời gian và chúng ta không thể tự động hoá được mọi thứ. Nên tahy vì vậy việc sử dụng Dockerfile sẽ giúp chúng ta có thể tạo ra các image 1 cách tự động không cần phải thực thi nhiều dòng lệnh nữa.
## 4. Docker Volume
``` Docker Volume là một cơ chế để duy trì việc tạo ra và sử dụng dữ liệu của Docker Container```

&nbsp;&nbsp;&nbsp;&nbsp;Bằng cách sử dụng Docker Volume chúng ta có thể dễ dàng quản lí các tác vụ của việc sử dụng container cũng như việc sao lưu dữ liệu và volume độc lập với vòng đời tồn tại của container
## 5. Docker Compose
``` Docker Compose là một công cụ dùng để tạo và chạy nhiều container cùng 1 lúc```

&nbsp;&nbsp;&nbsp;&nbsp;Với Docker Compose chúng ta sẽ sử dụng file dạng yaml để thiết đặt các việc tinh chỉnh cho các dịch vụ của ứng dụng. Sau đó chỉ với 1 vài dòng lệnh cơ bản chúng ta có thể tạo ra và kích hoạt tất cả các dịch vụ mà chúng ta đã thiết đặt trước đó.

# 1 số hình ảnh minh hoạ cho việc sử dụng docker
![img](https://miro.medium.com/max/1400/1*vb_5008Zbt_pHj7qx44p0Q.png)
![img](https://devopedia.org/images/article/101/8323.1565281088.png)

**Comment by TeamTCV1** [comment]
.

**Comment by TeamTCV1** [comment]
1, Khái niệm
Docker là một nền tảng cho developers và system admin để phát triển, triển khai và chạy ứng dụng với container. Nó cho phép tạo các môi trường độc lập và tách biệt để khởi chạy và phát triển ứng dụng-môi trường này được gọi là container. Khi cần triển khai lên bất kỳ server nào chỉ cần run container của Docker thì ứng dụng sẽ được khởi chạy ngay lập tức.
Container: Không giống như VMs, Container không cung cấp sự ảo hóa về phần cứng. Một Container cung cấp ảo hóa ở cấp hệ điều hành bằng một khái niệm trừu tượng là “user space”. Sự khác nhau lớn nhất của Container và VMs là Container có thể chia sẻ host system’s kernel với các container khác. Mô hình mô tả Container:
![Container](https://user-images.githubusercontent.com/95847728/216293725-85f1e8c8-fe12-458c-a8ab-402843607400.png)
