### ISSUE TITLE
Docker_error#1

### ISSUE THREAD

**Issue by TeamTCV1** [Hunter1202/se2022-15.2#27]
![image](https://user-images.githubusercontent.com/95847728/218700885-6a36f104-e1fc-4813-86b0-82f5acd6ab80.png)

**Comment by Thefuckingdead** [comment]
Lỗi của ông là như này đúng không 


https://user-images.githubusercontent.com/95278548/219015676-044c8d44-d10f-46ff-b729-cd9edf1cc1e3.mp4

<hr>

Ông cài thử Folder này đi


[docker_real.zip](https://github.com/Hunter1202/se2022-15.2/files/10742317/docker_real.zip)

Sau đấy ông giải nén ra và gõ lệnh build vs run như bình thường. Tôi đã thử và thực hiện được rồi này 


https://user-images.githubusercontent.com/95278548/219016610-30459fa8-d158-46b0-9eb5-cb672ab6040d.mp4
