### ISSUE TITLE
Kết nối tới cơ sở dữ liệu (MySQL)

### ISSUE THREAD

**Issue by Hunter1202** [Hunter1202/se2022-15.2#5]
# Lỗi kết nối JDBC

Tôi gặp lỗi khi kết nối project với database qua jdbc, ae đọc lỗi xem sửa giúp tôi được k?
![image](https://user-images.githubusercontent.com/94958811/207505576-9bacea7f-e9ee-47f5-9c38-88700e6ee7b0.png)

code:

![image](https://user-images.githubusercontent.com/94958811/207505768-19256a83-927a-4886-b356-11460b3f3393.png)
![image](https://user-images.githubusercontent.com/94958811/207505798-35b8a916-b5d7-4cb3-8129-471ec500a2cf.png)
![image](https://user-images.githubusercontent.com/94958811/207505813-abe7814c-02b7-4b0a-aa72-b9aa404c74a9.png)

**Comment by BToopS2** [comment]
ô đã add connectorJ.jar chưa ? 
[https://stackoverflow.com/questions/472896/place-mysql-connector-jar-in-web-inf-lib-of-my-war-instead-of-in-catalina-home](https://stackoverflow.com/questions/472896/place-mysql-connector-jar-in-web-inf-lib-of-my-war-instead-of-in-catalina-home?fbclid=IwAR3sD4Ezh8jj22tpxvJ2_7ceoAtZb6HpeP_sr1rDRJmsQkztvL1y7ecbtdU)
đọc thử cái này xem nhé

**Comment by Hunter1202** [comment]
oke cảm ơn ae để tôi thử xem sao

**Comment by Hunter1202** [comment]
Kết nối chạy ngon lành r nhé ae

![image](https://user-images.githubusercontent.com/94958811/207758579-cbb1369b-b6fd-4012-bed1-f256810ada8b.png)

**Comment by Hunter1202** [comment]
# Lỗi kết nối JDBC bị lỗi khi triển khai qua Docker 

![Image](https://user-images.githubusercontent.com/94958811/208350108-8f159a38-54de-4dd9-ab97-6d95b9002bd8.png)

Nguyên nhân: Do chưa tạo 1 image để kết nối với cơ sở dữ liệu
Tình trạng: Chưa fix

**Comment by Hunter1202** [comment]
#Fix lỗi kết nối JDBC qua Docker
- Giải pháp:
+ Tạo 1 container cho MySQL Database
+ Link container của Web với container của Database
- Kết quả:
![image](https://user-images.githubusercontent.com/94958811/218819338-260a8bb1-0c30-4e20-9188-5db59289b61e.png)
