### ISSUE TITLE
Triển khai 1 Website bằng Java

### ISSUE THREAD

**Issue by Hunter1202** [Hunter1202/se2022-15.2#9]
Tổng quan về website:
- Người dùng đăng ký tài khoản, mật khẩu, thông tin cá nhân
- Dữ liệu được trả về xử lý và hiện thông tin lên 
- Môi trường sử dụng: idle Eclipse, JDK15, server tomcat 9.0.62

**Comment by Hunter1202** [comment]
GIao diện nhập thông tin người dùng
![image](https://user-images.githubusercontent.com/94958811/207771664-e3a19821-1941-4261-9585-be364686b2ab.png)
Kết quả trả về
![image](https://user-images.githubusercontent.com/94958811/207771709-85b8b7d3-1389-43dc-8c4e-31c6a43dbf22.png)

src code updated

**Comment by Hunter1202** [comment]
@Thefuckingdead @BToopS2 làm lại giao diện giúp tôi nhé

**Comment by Thefuckingdead** [comment]
@Hunter1202 Ok
